---
title: "Kenya External Debt Register"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,warnings = FALSE, message = FALSE)
```

## Currency Composition of Kenya's External Debt


```{r}
library(tidyverse)
library(data.table)

public_debt <- fread("data/kenya_public_debt.csv")
public_debt <- public_debt[!is.na(amount_outstanding_as_at_30_06_2023_fx)]
number_curr_df = public_debt[, .(number_curr =.N), 
            by = .(president, curr)]


p = ggplot(number_curr_df, aes(x = reorder(president, -number_curr), y = number_curr, fill = curr)) +
    geom_col() +
    coord_flip() +
        scale_fill_manual(values =c( "#386CB0", "#F0027F",
                                "#BF5B17","#1B9E77", "#D95F02", "#7570B3", "#66A61E", "#E6AB02",
                                "#A6761D", "#2BB07FFF", "#C2DF23FF", "#38598CFF", "#482173FF", "#85D54AFF",
                                "#1E9B8AFF", "#51C56AFF", "#FDE725FF", "#2D708EFF", "#433E85FF",
                                "#25858EFF", "#440154FF",
                                "#7FC97F",  "#E7298A",
                                "#BEAED4", "#FDC086", "#FFFF99")) +
    labs(title = "Number of loans by president", x = "President", y = "Number of loans") +
    theme_minimal()

p
```


## Loan Duration by President


```{r}

ggplot(public_debt, aes(x = duration_payment_yrs)) +
    geom_histogram(binwidth = 1) +
    facet_wrap(~president) +
    labs(title = "Facet histogram of loan duration by president", x = "Duration (years)", y = "Count") +
    theme_minimal()

```
